config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "users/sessions#root"
  end
  get 'users/show'
  get 'friends/new'
  get 'reactions/new'
  get 'comments/new'
  get 'timeline', to: 'posts#timeline'
  post 'timeline', to: 'posts#create'
  post 'like', to: 'reactions#create'
  resources :comments
  resources :posts
  resources :friends
  get 'main/home'
 
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'callbacks',

  }
  resources :users
  #match '*path', to:'users/sessions#root', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :reactions, as: :resource, dependent: :destroy

  validates :content, length: {maximum: 120}, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    comment = Comment.new(comment_params)
    comment.save
    stay_on_same_path
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    stay_on_same_path 
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def to_show_user_data comment
    User.find(comment.user_id)
  end
  
  def comment_owner?(comment)
    current_user.id == comment.user_id
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment-image d-inline">
    <%= image_tag to_show_user_data(comment).profile_pic.variant(resize: "100x100!") %>
  </div>
  <div class="comment-block d-inline-block">

    <div class="comment-owner">

      <%= to_show_user_data(comment).name.capitalize %>
    </div>
    <div class="text-clr d-inline-block">
      <%= comment.content %>
    </div>
    <div class="trash">
      <% if comment_owner?(comment) %>
        <%= link_to 'x', comment_path(comment), method: :delete %>
      <% end %>
    </div>
  </div>
  <div class="comment-likes">
    <%= render 'reactions/comment_like', comment: comment %>
    <%= likes_counter(comment) %>
    <%= dislikes_counter(comment) %>
    <%= render 'reactions/comment_dislike', comment: comment %>
  </div>
</div>

app/views/comments/_new.html.erb
<%= form_with(model: post_id.comments.build, url: comments_path, id:"form", class: "ml-1") do |c| %>
  <%= c.hidden_field :user_id, value: current_user.id %>
  <%= c.hidden_field :post_id, value: post_id.id %>
  <%= c.text_area :content, class:"comment-area px-3 text-clr" %>
  <%= c.submit 'Comment', class:"d-none" %>
<% end %>


<script>
    $('#form textarea').keydown(function(e) {
        if (e.keyCode == 13) {
            e.preventDefault();
            $('#form').submit();
        }
    });
</script>