config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "users/sessions#root"
  end
  get 'users/show'
  get 'friends/new'
  get 'reactions/new'
  get 'comments/new'
  get 'timeline', to: 'posts#timeline'
  post 'timeline', to: 'posts#create'
  post 'like', to: 'reactions#create'
  resources :comments
  resources :posts
  resources :friends
  get 'main/home'
 
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'callbacks',

  }
  resources :users
  #match '*path', to:'users/sessions#root', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_pic
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy
  has_many :friends, dependent: :destroy 
  has_many :reactions, through: :posts, dependent: :destroy
  has_many :reactions, through: :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  validates :name, presence: true, length: { minimum: 3}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
          omniauth_providers: %i[facebook]
  validates :dob, presence: true, format: /([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))/, unless: -> { from_omniauth? }
  validate :check_dob, unless: -> { from_omniauth? }
  validate :default_image
  
  def self.myfriends(friendslist)
    User.where(id: friendslist.collect(&:friend_uid))
  end

  def self.requestaccepted(friend)
    User.where(id: friend.collect(&:user_id))
  end
  
  def self.pending(user)
    a = user.collect(&:user_id)
    User.where(id: a).order("position(id::text in '#{a.join(',')}')")
  end
  
  def self.others(others_users,current_user)
    User.where.not(id: others_users.collect(&:friend_uid)).where.not(id: current_user.id).where.not(id: others_users.collect(&:user_id))
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.first_name
      user.password = Devise.friendly_token[0,20]
    end
  end

  protected
  def check_dob
    if dob
      errors.add(:dob, "can't be in future") if dob > Date.today
    end
  end

  private
  def from_omniauth?
    provider && uid
  end

  def default_image
    if !self.profile_pic.attached?
      if self.gender == 'male'
        self.profile_pic.attach(io: File.open(Rails.root.join("app", "assets", "images", "male.png")), filename: 'male.png' , content_type: "image/jpg")
      elsif self.gender == 'female'
        self.profile_pic.attach(io: File.open(Rails.root.join("app", "assets", "images", "female.png")), filename: 'female.png' , content_type: "image/jpg")
      else
        self.profile_pic.attach(io: File.open(Rails.root.join("app", "assets", "images", "neutral.png")), filename: 'neutral.png' , content_type: "image/jpg")
    end
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def after_sign_up_path_for(resource)
    timeline_path
  end

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_to do |format|
        format.js { render 'devise/shared/errors_signup' }
      end
end
  end
 
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
 # before_action :configure_sign_in_params, only: [:create]
  # def after_sign_in_path_for(resource)
  #   redirect_to new_user_session_path || super
  # end
  # GET /resource/sign_in
  def new
    super
  end


  def root
    if signed_in?
      redirect_to timeline_path
    else
      redirect_to  new_user_session_path
    end
  end

  # POST /resource/sign_in
  def create
    super
    # if resource.save
    #   redirect_to reso_path
    # else
    #   redirect_to users_path
    # end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    c = @user.posts.ids
    @user_photos = ActiveStorage::Attachment.where(record_type:'Post').where(record_id:c).where.not(name:'profile_pic').order(created_at: :desc).limit(8)
  end
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_with_password(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:password,:name,:profile_pic,:dob,:email,:current_password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def my_posts user
        Post.myPosts(user)
    end
   
end

app/views/users/edit.html.erb
<%= form_for(@user) do |user| %>
    <%= user.text_field :name,id:'update_name' %><br/>
    <%= user.email_field :email %><br/>
    <%= user.date_field :dob %><br/>
    <%= user.file_field :profile_pic %><br/>
    <%= image_tag @user.profile_pic,style:'width:5%; border-radius:50%' %><br/>
    <%= user.label :current_password %>
    <%= user.password_field :current_password %>
    <p>New Password</p>
    <%= user.password_field :password %>
      <%= user.password_field :password_confirmation %>
    <%= user.submit %>
<% end %>
<%= link_to 'Back',user_path(@user) %>

app/views/users/show.html.erb
<!-- header start -->
<nav class="container mt-2">
  <div class="profile-details my-2 d-flex">
    <div class="w-25 p-1 m-0">
      <%= image_tag @user.profile_pic ,style:'width:50%; border-radius:50%' %>
    </div>
  <div class="w-75">
    <div class="mt-2">
      <h3 class="w-75 float-left"><%= @user.name %></h3>
      <% if current_user == @user %>
        <%= link_to fa_icon('wrench'),edit_user_path(@user),class:'float-left mt-2' %>
      <% end %>
      <div class="w-100 float-left">
        <p>Some status.......</p>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<!-- header end -->

</div>
  <div class="nav nav-tabs d-flex justify-content-center" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Posts</a>
    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Information</a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Photos</a>
  </div>
</nav>

<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
  <div class="w-100 d-flex align-items-center justify-content-center" style="height:20vh;overflow-x:hidden">
    <% @user_photos.each do |image| %>
    <%= image_tag image,style:'width:100px;height:100px;border-radius:5px',class:'mx-1' %>
    <% end %>
</div>
  <% my_posts(@user).each do |p| %>
  <div class="jumbotron">
    <div class="pic-name-date">
      <div class="profile-image d-inline float-left">
        <%= image_tag is_post_creator_image(p).profile_pic, class: 'm-auto' %>
      </div>
      <div class="post-text d-inline float-left ml-3" style="width: 92%">
        <%= is_post_creator_name(p) %>

        <% if post_owner?(p) %>
          <%= link_to fa_icon("trash"), post_path(p), method: :delete, class: "float-right" %>
        <% end %>
        <small class="d-block">
          <%= p.created_at.strftime("%I:%M %p, %b %d '%y") %>
        </small>
      </div>
      <div class="clearfix"></div>
    </div>

    <div class="content text-clr">
      <%= p.content unless p.content.empty? %>
    </div>

    <% p.post_pic.each do |y| %>
      <%= image_tag y.variant(resize: "100x100!") %>
    <% end %>

    <div class="reactions">
      <%= render 'reactions/like', p: p %>
      <div class="d-inline-block">
        <%= likes_counter(p) %>
      </div>
      <div class="d-inline-block">
        <%= dislikes_counter(p) %>
      </div>
      <%= render 'reactions/dislike', p: p %>
    </div>

    <div class="comment-size">
    <%= render p.comments %>
    </div>

    <div class="new-comment d-flex">
      <div class="comment-image d-inline-block">
        <%= image_tag current_user.profile_pic, class: 'm-auto' %>
      </div>
      <div class="d-inline-block w-100">
      <%= render 'comments/new', post_id: p %>
      </div>
    </div>

  </div>
<% end %></div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab"><%= @user.name %>
<%= @user.dob %>
<%= @user.email %>
<%= image_tag @user.profile_pic ,style:'width:5%; border-radius:50%' %>
<% if current_user == @user %>
<%= link_to 'Edit',edit_user_path(@user) %>
<% end %></div>
  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...</div>
</div>