config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "users/sessions#root"
  end
  get 'users/show'
  get 'friends/new'
  get 'reactions/new'
  get 'comments/new'
  get 'timeline', to: 'posts#timeline'
  post 'timeline', to: 'posts#create'
  post 'like', to: 'reactions#create'
  resources :comments
  resources :posts
  resources :friends
  get 'main/home'
 
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'callbacks',

  }
  resources :users
  #match '*path', to:'users/sessions#root', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :check_if_liked, only: [:create]
  before_action :check_if_disliked, only: [:create]
  def new
  end

  def create
    Reaction.create(params_reactions)
    stay_on_same_path
  end

  private

  def params_reactions
    params.require(:reaction).permit(:user_id, :like, :dislike, :resource_id, :resource_type)
  end

  def check_if_liked
    like = Reaction.find_by(user_id: params[:reaction][:user_id], resource_id: params[:reaction][:resource_id] ,
                         resource_type: params[:reaction][:resource_type], like: true)

    if params[:reaction][:dislike] && like.present?
      like.update_attributes(like: nil,dislike: true)
      stay_on_same_path
    elsif like.present?
      like.destroy
      stay_on_same_path
    end
  end

  def check_if_disliked
    dislike = Reaction.find_by(user_id: params[:reaction][:user_id], resource_id: params[:reaction][:resource_id] ,
                            resource_type: params[:reaction][:resource_type], dislike: true)


    if params[:reaction][:like] && dislike.present?
      dislike.update_attributes(dislike: nil,like: true)
      stay_on_same_path
    elsif dislike.present?
        dislike.destroy
        stay_on_same_path
    end
  end

  def stay_on_same_path
    prev = Rails.application.routes.recognize_path(request.referrer)
    if prev[:controller] == "posts"
        redirect_to timeline_path
    else
      session[:return_to] ||= request.referer
      redirect_to session.delete(:return_to)
    end
  end


end

app/helpers/reactions_helper.rb
module ReactionsHelper
  def likes_counter(resource)
    resource.reactions.where(like: true).count
  end

  def dislikes_counter(resource)
    resource.reactions.where(dislike: true).count
  end
  
 
end

app/views/reactions/_comment_dislike.html.erb
<%= form_with(model: comment.reactions.build, url: like_path, class:"d-inline-block") do |r| %>
  <%= r.hidden_field :user_id, value: current_user.id %>
  <%= r.hidden_field :resource_id, value: comment.id %>
  <%= r.hidden_field :resource_type, value: "Comment" %>
  <%= r.hidden_field :dislike, value: true %>
  <%= r.button fa_icon("thumbs-down"), class: "button my-button bg-transparent", id: "register-button" %>
<% end %>

app/views/reactions/_comment_like.html.erb
<%= form_with(model: comment.reactions.build, url: like_path, class:"d-inline-block") do |r| %>
  <%= r.hidden_field :user_id, value: current_user.id %>
  <%= r.hidden_field :resource_id, value: comment.id %>
  <%= r.hidden_field :resource_type, value: "Comment" %>
  <%= r.hidden_field :like, value: true %>
  <%= r.button fa_icon("thumbs-up"), class: "button my-button bg-transparent", id: "register-button" %>
<% end %>

app/views/reactions/_dislike.html.erb
<%= form_with(model: p.reactions.build, url: like_path, class:"d-inline-block") do |r| %>
  <%= r.hidden_field :user_id, value: current_user.id %>
  <%= r.hidden_field :resource_id, value: p.id %>
  <%= r.hidden_field :resource_type, value: "Post" %>
  <%= r.hidden_field :dislike, value: true %>
  <%= r.button fa_icon("thumbs-down"), class: "button my-button bg-transparent", id: "register-button" %>
<% end %>

app/views/reactions/_like.html.erb
<%= form_with(model: p.reactions.build, url: like_path, class:"d-inline-block") do |r| %>
  <%= r.hidden_field :user_id, value: current_user.id %>
  <%= r.hidden_field :resource_id, value: p.id %>
  <%= r.hidden_field :resource_type, value: "Post" %>
  <%= r.hidden_field :like, value: true %>
  <%= r.button fa_icon("thumbs-up"), class: "button my-button bg-transparent", id: "register-button" %>
<% end %>