config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "users/sessions#root"
  end
  get 'users/show'
  get 'friends/new'
  get 'reactions/new'
  get 'comments/new'
  get 'timeline', to: 'posts#timeline'
  post 'timeline', to: 'posts#create'
  post 'like', to: 'reactions#create'
  resources :comments
  resources :posts
  resources :friends
  get 'main/home'
 
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'callbacks',

  }
  resources :users
  #match '*path', to:'users/sessions#root', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'
end

app/views/layouts/_footer.html.erb
<div class="float-left px-2 w-25 alignment">
  <div class="w-30 float-left">
    <%= link_to user_path(current_user) do %>
    <div class="d-flex footer-profile-image"><%= image_tag current_user.profile_pic, class: 'm-auto' %></div>
      <% end %>
  </div>
  <div class="w-80 float-right pl-2">
    <p class="text-white m-0 mt-1"><%= link_to current_user.name.capitalize,user_path(current_user) %> </p>
    <small class="tagline">No status....</small>
  </div>
  <div class="clearfix"></div>
</div>
<div class="w-75 text-center float-left footer-central alignment">
  <div class="w-50 float-left">
    <div class="dropdown">
      <button type="button" data-toggle="dropdown" class="btn btn-outline-light border-0">
        <%= image_tag 'Path 85', class: "dropdown-toggle", data_toggle: "dropdown" %>
         <span class="badge badge-pill badge-danger float-right"><%= notifications_count if notifications_count > 0 %></span>
      </button>
      <div class="dropdown-menu">
        <% notification_user.each do |friend| %>
        <h5><%= friend.name.capitalize %> sent friend request </h5>
        <small><%=distance_of_time_in_words(Time.now,notification_time(friend)) %> ago</small>
         <%= link_to 'Accept',friend_path(friend),method: :patch %>
        <%= link_to 'Cancel',friend_path(friend),method: :delete %>
        <% end %>
      </div>
      <button type="button" data-toggle="dropdown" class="btn btn-outline-light border-0">
        <%= image_tag 'Group 958', class: "dropdown-toggle", data_toggle: "dropdown" %>
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Link 1</a>
        <a class="dropdown-item" href="#">Link 2</a>
        <a class="dropdown-item" href="#">Link 3</a>
      </div>
      <button type="button" data-toggle="dropdown" class="btn btn-outline-light border-0">
        <%= image_tag 'Path 90', class: "dropdown-toggle", data_toggle: "dropdown" %>
      </button>
      <div class="dropdown-menu">
      <h5>some text</h5>
      <a class="dropdown-item" href="#">Link 1</a>
       <%= link_to 'Profile', user_path(current_user),class:'dropdown-item' %>
       <%= link_to 'Logout', destroy_user_session_path,class:'dropdown-item' %>
      </div>
      <button type="button" data-toggle="dropdown" class="btn btn-outline-light border-0">
        <%= image_tag 'Path 83', class: "dropdown-toggle", data_toggle: "dropdown" %>
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Link 1</a>
        <a class="dropdown-item" href="#">Link 2</a>
        <a class="dropdown-item" href="#">Link 3</a>
      </div>
      <button type="button" data-toggle="dropdown" class="btn btn-outline-light border-0">
        <%= image_tag 'Group 45', class: "dropdown-toggle", data_toggle: "dropdown" %>
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Link 1</a>
        <a class="dropdown-item" href="#">Link 2</a>
        <a class="dropdown-item" href="#">Link 3</a>
      </div>
    </div>
  </div>
  <div class="w-50 float-left">
    <p>Text</p>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="main-sidebar">
  <div class="sidebar-icons mt-3">
    <%= image_tag 'logo.png', class: "logo-f" %>
    <div class="sidebar-icons-menu mt-2">
      <div class="menu">
        <h6><strong class="text-color">Menu</strong></h6>
        <ul class="side-menu">
          <li class="text-color"><%= link_to timeline_path do %><%= image_tag 'noun_Newspaper_772219 (1).png', class: "icon"%> News<% end %></li>
          <li class="text-color"><%= image_tag 'noun_message_2043227@2x.png', class: "icon"%> Messages <span class="badge badge-pill badge-danger float-right">8</span></li>
          <li class="text-color"><%= link_to friends_path do %><%= image_tag 'noun_friends_1297819@2x.png', class: "icon"%>Friends<% end %></li>
          <li class="text-color"><%= image_tag 'noun_event_1379383@2x.png', class: "icon"%> Events</li>
          <li class="text-color"><%= image_tag 'Group 1119@2x.png', class: "icon"%> Communities</li>
          <li class="text-color"><%= image_tag 'noun_pages_734946@2x.png', class: "icon"%> Pages</li>
          <li class="text-color"><%= image_tag 'noun_Box_1276334@2x.png', class: "icon"%> Apps</li>
        </ul>
      </div>
      <div class="shortcuts mt-1">
        <h6><strong class="text-color">Authors</strong></h6>
        <ul class="side-menu">
          <li class="text-color"><%= image_tag 'octocat.png',class:'sidebar-icon' %><%= link_to 'Inzi',"https://github.com/inhaq",target:"_blank",style:"font-weight:500" %></li>
          <li class="text-color"><%= image_tag 'octocat.png',class:'sidebar-icon' %><%= link_to 'Zlaya',"https://github.com/zlayabekrija",target:"_blank",style:"font-weight:500" %></li>
        </ul>
      </div>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    </div>
  </div>
</div>

app/views/layouts/_stories.html.erb
<% if controller_name == 'users'%>
<div class="counts d-flex align-items-center justify-content-center text-primary p-2 text-center">
    <div class="w-25">
        <p class="mb-0"><%= @user.posts.count %></p>
        <p class="w-100">Posts</p>
    </div>
    <div class="w-25">
        <p class="mb-0"><%= @user.reactions.count %></p>
        <p class="w-100">Reactions</p>
    </div>
    <div class="w-25">
        <p class="mb-0"><%= @user.comments.count %></p>
        <p class="w-100">Comments</p>
    </div>
    <div class="w-25">
        <p class="mb-0"><%= @user.friends.count %>
        <p class="w-100">Friends</p>
    </div>
</div>
<div>
    <div class="w-100">
        <h5 class="float-left ml-3">About</h5>
        <p class="float-right text-primary mr-3">More</p>
          <div class="clearfix"></div>
    </div>
    <div class="w-100 text-left">
    <p class="w-100 ml-3"><%= current_user.dob %>, <%= current_user.gender.capitalize %></p>
    </div>
  </div>
  <% elsif controller_name == 'posts' %>
  <div class="counts d-flex align-items-center justify-content-center text-primary p-2 text-center">
    <div class="w-25">
        <p class="mb-0"><%= current_user.posts.count %></p>
        <p class="w-100">Posts</p>
    </div>
    <div class="w-25">
        <p class="mb-0"><%= current_user.reactions.count %></p>
        <p class="w-100">Reactions</p>
    </div>
    <div class="w-25">
        <p class="mb-0"><%= current_user.comments.count %></p>
        <p class="w-100">Comments</p>
    </div>
    <div class="w-25">
        <p class="mb-0"><%= current_user.friends.count %>
        <p class="w-100">Friends</p>
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Funbook</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag 'logo.png', rel: 'icon', type: 'image/png' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="background-color: #f5f5f5">
<%# flash.each do |message_type, message| %>
<!--        <div class="alert alert-<%#= message_type %>"><%#= message %></div>-->
<%# end %>
<% if signed_in? %>
  <div class="sidebar">
    <%= render 'layouts/sidebar' %>
  </div>
<% end %>
<%= yield if !signed_in? %>
<% if signed_in? %>
  <div class="container-fluid clearfix p-0 mb-5" style="margin-left: 260px;width:calc(100% - 260px);">
    <div class="mid-portion">
      <%= yield %>
    </div>
    <div class="stories">
        <%= render 'layouts/stories' %>
    </div>
    <%#= image_tag current_user.profile_pic %>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </div>
<% end %>
</body>
</html>